### ISSUE TITLE
Does not work in this case

### ISSUE THREAD

**Issue by legluondunet** [kylon/Lipx#1]
Hello,
I would like to use your tool to patch a rom and it won't work.
Try this:
search and find this SNES rom: Chrono Trigger (US).smc 
download the french translation patch from this site:
https://traf.romhack.org/?p=patchs&pid=1071&aff=coms

Try to patch the USA rom: 
$ python ./lipx.py  -a "SNES rom: Chrono Trigger (US).smc" "Chrono Trigger (Fr) v1.03.ips"
or
$ python3 ./lipx.py  -a "SNES rom: Chrono Trigger (US).smc" "Chrono Trigger (Fr) v1.03.ips"
it won't work.

Thank you for your help.

Config: Ubuntu 18.04

**Comment by kylon** [comment]
Hi,

Unfortunately i'm too busy, i can look at this in july.
Thank you for the report

**Comment by kylon** [comment]
i'm late, eh
anyway the README of the patch says a headerless rom is required (.sfc), but you were using a .smc rom
