### ISSUE TITLE
Support for user specified output files (+a working? patch).

### ISSUE THREAD

**Issue by Zuccace** [kylon/Lipx#2]
Hi. I decided to learn some python to fix this issue.
Here's my [patch](https://raw.githubusercontent.com/Zuccace/zucca-overlay/8cccb19b890ee89939564e9de3803e173acfb5a4/dev-util/lipx/files/user-definable-output.patch).
Please test it well if you are considering using it. This was _really_ my first python coding I've ever done.

**Comment by kylon** [comment]
Hi,

thanks, i simplified your patch a bit and committed the changes
