### ISSUE TITLE
Improved usage() for system-wide installations.

### ISSUE THREAD

**Issue by Zuccace** [kylon/Lipx#4]
Replacing static 'lipx.py' with dynamic will display help text that is consistent with the actual installed file (for example if installed as /usr/bin/lipx).
```
def usage():
    this = os.path.basename(sys.argv[0])
    print('\nLipx v' + VERSION + ' - Linux IPS tool\n\n' +
           'Usage:\n\n' +
           '    == Apply patch\n' +
           '    ' + this + ' -a originalFile patchFile\n\n' +
           '    == Create a copy and apply the patch - original is untouched\n' +
           '    ' + this + ' -ab originalFile patchFile [outputFile]\n\n' +
           '    == Create IPS patch\n' +
           '    ' + this + ' -c originalFile modifiedFile [outputFile]\n\n' +
           'Arguments:\n' +
           '    [] optional argument\n')

    sys.exit(1)
```

**Comment by kylon** [comment]
_basename_ will always return "lipx.py", also help should not print any path

**Comment by Zuccace** [comment]
Yes. That's the point.
For example I have lipx.py installed as '/usr/bin/lipx'.
Now the help text shows the command as **lipx** and _not_ as **lipx.py**.

If the package maintainer chooses to install **lipx.py** as **/usr/bin/ips-patcher**, then the help screen would show **ips-patcher** as the command.

So the basename is there exactly for stripping the leading path. ;)

**Comment by kylon** [comment]
oh, got it
i didn't thougth about that
