### ISSUE TITLE
"python" shebang

### ISSUE THREAD

**Issue by 2mac** [kylon/Lipx#7]
The current shebang at the top of the script references `python` but this program requires Python 3. Most systems refer to Python 3.x as `python3`.

**Comment by rofl0r** [comment]
> this program requires Python 3.

works fine here with python 2.7.18.

**Comment by 2mac** [comment]
> works fine here with python 2.7.18.

How are you running it? If you're running the latest code, the shebang is already changed to call python3. You probably have python 3 installed on your system as well, and it's calling that. This program uses syntax that is illegal in python 2, and it doesn't import any of the modules that would enable it to be compatible. The reason I opened this issue in the first place is because my system tried to run it in python 2 with the old shebang and it failed. I'm 99% sure you ran it with python 3 without realizing.

**Comment by rofl0r** [comment]
i only have python2 installed and executed "python lipx.py ....". both creating a patch and applying worked without issues.

**Comment by 2mac** [comment]
Hmm, okay I just tested this and it does appear to work. I guess the newer python 2 versions accept the python 3 print syntax. Either way, `python` in the shebang is not portable, and the README says the program is tested with python 3.
